kind: pipeline
name: default

steps:
- name: build
  image: nginx
    commands:
    - echo "building..."
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: u_docker
    password:
      from_secret: p_docker
    repo: squedge/nginxHellowWorld
    tags: "test_1"
